### ISSUE TITLE
SSHByPassword and SSH does not support MDNS host addresses

### ISSUE THREAD

**Issue by JLLeitschuh** [jcabi/jcabi-ssh#37]
```java
Invalid IP address of the server `roborio-191-frc.local`
java.lang.IllegalArgumentException: Invalid IP address of the server `roborio-191-frc.local`
	at org.apache.commons.lang3.Validate.matchesPattern(Validate.java:875)
	at com.jcabi.ssh.SSHByPassword.<init>(SSHByPassword.java:91)
```

This is a valid SSH host address.

---

# Workaround

Thanks to this [stackoverflow post](http://stackoverflow.com/a/15788605/3708426).

```java
InetAddress address = InetAddress.getByName("roborio-191-frc.local");
String useThisAddress = address.getHostAddress();  // Use this in the constructor call
```

**Comment by dmarkov** [comment]
@yegor256 please do something about it, see [par.21](http://at.teamed.io/policy.html#21)

**Comment by yegor256** [comment]
@JLLeitschuh definitely a bug, we'll try to fix it ASAP, thanks for reporting!

**Comment by dmarkov** [comment]
@jrdalpra this task is for you, keep [these principles](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) in mind, and don't hesitate to ask any technical questions; The budget of this issue is **30 mins**, which is exactly how much will be paid when the task is *done* (see [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) for explanation)

**Comment by jrdalpra** [comment]
@JLLeitschuh the issue is already solved as you can see here https://github.com/jcabi/jcabi-ssh/blob/master/src/main/java/com/jcabi/ssh/SSHByPassword.java#L91

It was solved by this commit https://github.com/jcabi/jcabi-ssh/commit/41dfaee1b1641a43836bb36a618ec76cb123d467#diff-b22a1bfa40970bf76b871237ca10029b

I think the issue can be closed.

Are you using the lastest version of jcabi-ssh?

Thanks.

**Comment by jrdalpra** [comment]
@JLLeitschuh can you see if the problem was solved? 

@dmarkov @yegor256 A got no answer from @JLLeitschuh. What can I do?

**Comment by yegor256** [comment]
@jrdalpra let's wait a little bit, at least a week

**Comment by jrdalpra** [comment]
@yegor256 what about this http://at.teamed.io/policy.html#22?

**Comment by jrdalpra** [comment]
@JLLeitschuh  @dmarkov  @yegor256 can we close now?

**Comment by yegor256** [comment]
@rultor release, tag is `1.5.1`

**Comment by jrdalpra** [comment]
@yegor256 @dmarkov @JLLeitschuh  can you close the issue, please?

**Comment by yegor256** [comment]
@JLLeitschuh please, try version 1.5.1, we believe that it will work without a problem

**Comment by JLLeitschuh** [comment]
Sorry, I'll update when I get a chance. We are about to do our release to 4000 FIRST Robotics Teams. Things are kind of hectic right now.

Off topic:
@yegor256 I enjoy reading your blog. I don't necessarily agree with everything but you make some good points.
And the code behind this library is solid.

**Comment by jrdalpra** [comment]
@JLLeitschuh <https://github.com/JLLeitschuh> can you close the issue?

On Saturday, January 2, 2016, Jonathan Leitschuh <notifications@github.com>
wrote:

> Sorry, I'll update when I get a chance. We are about to do our release to
> 4000 FIRST Robotics Teams. Things are kind of hectic right now.
>
> Off topic:
> @yegor256 <https://github.com/yegor256> I enjoy reading your blog. I
> don't necessarily agree with everything but you make some good points.
> And the code behind this library is solid.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jcabi/jcabi-ssh/issues/37#issuecomment-168422953>.
>


-- 
José Volmei Dal Prá Junior - (49) 9112 9359
Bacharel em Ciência da Computação - UnoChapecó
Pós-Graduado em Desenvolvimento de Software Com Java - Unoesc Xxe
Consultor Java e TotalCross
https://github.com/jrdalpra
http://www.kombo.com.br/meucurriculo/jrdalpra
http://www.linkedin.com/in/jrdalpra
msn: jr_dalpra@hotmail.com
skype: jrdalpra
e-mail: jrdalpra@gmail.com

**Comment by jrdalpra** [comment]
@yegor256 @dmarkov @JLLeitschuh can someone close this issue? I think it's solved and can be opened again if the problem continues to happen. Thanks.

**Comment by yegor256** [comment]
@JLLeitschuh pls close this ticket. and thanks for reading the blog )

**Comment by jrdalpra** [comment]
@yegor256 @dmarkov can't you close the issue? Seems that @JLLeitschuh  is having problems to close it.

**Comment by yegor256** [comment]
@dmarkov pls close it

**Comment by jrdalpra** [comment]
@yegor256 @dmarkov I solved the issue at the same day that it was assigned to me, but it's not closed yet. There was no problem with my solution because I just have tested and I saw that everything was ok. The issue's author not closed it right after my solution. My points will be calculated looking for the day that I delivered the solution or the day the issue will be closed. Thanks.

**Comment by JLLeitschuh** [comment]
I mean I see no reason why this wouldn't work.
I haven't had the opportunity to test it yet and probably won't until next week.
Anyways, nice job guys.

**Comment by dmarkov** [comment]
> @dmarkov pls close it

@yegor256 it is closed already

**Comment by jrdalpra** [comment]
@dmarkov can you remove the issue at netbout (were can I see how the process of closing issues at netbout works?)

**Comment by dmarkov** [comment]
@jrdalpra I just added **30 mins** to your account, many thanks for your contribution (AP-2DM15155RJ530392Y).. 330 hours and 39 mins spent here... +30 added to your rating, at the moment it is: [+158](http://www.netbout.com/b/36044?open=rating)

**Comment by jrdalpra** [comment]
@dmarkov @yegor256 see my message at netbout, please. thanks.

**Comment by dmarkov** [comment]
> @dmarkov @yegor256 see my message at netbout, please. thanks.

@jrdalpra sure, you are welcome
